structure(list(url = "https://www.ebi.ac.uk/gwas/rest/api/fernandopessoa", 
    status_code = 404L, headers = structure(list(server = "Apache-Coyote/1.1", 
        `cache-control` = "no-cache, no-store, max-age=0, must-revalidate", 
        `content-type` = "application/json;charset=UTF-8", `strict-transport-security` = "max-age=0", 
        date = "Tue, 06 Nov 2018 16:31:04 GMT", `x-application-context` = "application", 
        expires = "0", `x-xss-protection` = "1; mode=block", 
        pragma = "no-cache", `x-content-type-options` = "nosniff", 
        `x-frame-options` = "DENY"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/2", 
        headers = structure(list(server = "Apache-Coyote/1.1", 
            `cache-control` = "no-cache, no-store, max-age=0, must-revalidate", 
            `content-type` = "application/json;charset=UTF-8", 
            `strict-transport-security` = "max-age=0", date = "Tue, 06 Nov 2018 16:31:04 GMT", 
            `x-application-context` = "application", expires = "0", 
            `x-xss-protection` = "1; mode=block", pragma = "no-cache", 
            `x-content-type-options` = "nosniff", `x-frame-options` = "DENY"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"timestamp\":1541521864160,\"status\":404,\"error\":\"Not Found\",\"message\":\"No message available\",\"path\":\"/gwas/rest/api/fernandopessoa\"}"), 
    date = structure(1541521864, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.2e-05, 
    connect = 2.3e-05, pretransfer = 8.1e-05, starttransfer = 1.251715, 
    total = 1.251888)), class = "response")
