structure(list(url = "https://www.ebi.ac.uk/gwas/rest/api/studies/GCST000000", 
    status_code = 404L, headers = structure(list(server = "Apache-Coyote/1.1", 
        `cache-control` = "no-cache, no-store, max-age=0, must-revalidate", 
        `strict-transport-security` = "max-age=0", date = "Wed, 14 Nov 2018 15:01:38 GMT", 
        `x-application-context` = "application", expires = "0", 
        `x-xss-protection` = "1; mode=block", pragma = "no-cache", 
        `x-content-type-options` = "nosniff", `x-frame-options` = "DENY"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/2", 
        headers = structure(list(server = "Apache-Coyote/1.1", 
            `cache-control` = "no-cache, no-store, max-age=0, must-revalidate", 
            `strict-transport-security` = "max-age=0", date = "Wed, 14 Nov 2018 15:01:38 GMT", 
            `x-application-context` = "application", expires = "0", 
            `x-xss-protection` = "1; mode=block", pragma = "no-cache", 
            `x-content-type-options` = "nosniff", `x-frame-options` = "DENY"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = raw(0), date = structure(1542207698, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.7e-05, 
    connect = 2.8e-05, pretransfer = 9.9e-05, starttransfer = 0.054924, 
    total = 0.054962)), class = "response")
